/// Animation system — queued animations with tick-based progression.
use std::collections::VecDeque;

use ratatui::style::Color;
use sabacc_core::PlayerId;

/// A single animation to play.
#[derive(Debug, Clone)]
pub enum Animation {
    /// Show chip gain/loss on a player (reserved for future use).
    #[allow(dead_code)]
    ChipChange {
        player_id: PlayerId,
        delta: i8,
        duration_ms: u64,
    },
    /// Highlight a player's row.
    PlayerHighlight {
        player_id: PlayerId,
        #[allow(dead_code)]
        color: Color,
        duration_ms: u64,
    },
    /// Add a message to the log.
    LogMessage { text: String },
    /// Wait without visual effect (used in tests).
    #[allow(dead_code)]
    Pause { duration_ms: u64 },
}

/// Creates a PlayerHighlight animation for a bot turn (yellow, given duration).
pub fn bot_highlight(player_id: PlayerId, duration_ms: u64) -> Animation {
    Animation::PlayerHighlight {
        player_id,
        color: Color::Yellow,
        duration_ms,
    }
}

impl Animation {
    /// Returns the total duration of this animation in milliseconds.
    /// Instant animations (LogMessage) return 0.
    pub fn duration_ms(&self) -> u64 {
        match self {
            Self::ChipChange { duration_ms, .. }
            | Self::PlayerHighlight { duration_ms, .. }
            | Self::Pause { duration_ms, .. } => *duration_ms,
            Self::LogMessage { .. } => 0,
        }
    }
}

/// An animation currently in progress.
#[derive(Debug, Clone)]
pub struct ActiveAnimation {
    pub animation: Animation,
    pub elapsed_ms: u64,
}

impl ActiveAnimation {
    pub fn new(animation: Animation) -> Self {
        Self {
            animation,
            elapsed_ms: 0,
        }
    }

    /// Returns a value between 0.0 and 1.0 representing progress.
    #[allow(dead_code)]
    pub fn progress(&self) -> f64 {
        let dur = self.animation.duration_ms();
        if dur == 0 {
            1.0
        } else {
            (self.elapsed_ms as f64 / dur as f64).min(1.0)
        }
    }

    /// Returns true when the animation has completed.
    pub fn is_done(&self) -> bool {
        self.elapsed_ms >= self.animation.duration_ms()
    }

    /// Advance time by `delta_ms` milliseconds.
    pub fn tick(&mut self, delta_ms: u64) {
        self.elapsed_ms += delta_ms;
    }
}

/// A queue of pending animations.
#[derive(Debug, Clone, Default)]
pub struct AnimationQueue {
    pub queue: VecDeque<Animation>,
    pub current: Option<ActiveAnimation>,
}

impl AnimationQueue {
    pub fn new() -> Self {
        Self::default()
    }

    /// Push an animation onto the back of the queue.
    pub fn push(&mut self, anim: Animation) {
        self.queue.push_back(anim);
    }

    /// Returns true if there is a current animation or pending ones.
    pub fn is_animating(&self) -> bool {
        self.current.is_some() || !self.queue.is_empty()
    }

    /// Advance the animation state by one tick. Returns any log messages
    /// generated by instantly-completed animations.
    pub fn tick(&mut self, delta_ms: u64) -> Vec<String> {
        let mut messages = Vec::new();

        loop {
            if let Some(ref mut active) = self.current {
                active.tick(delta_ms);
                if active.is_done() {
                    // Collect log messages from completed animations
                    if let Animation::LogMessage { ref text } = active.animation {
                        messages.push(text.clone());
                    }
                    self.current = None;
                    // Continue to dequeue next
                } else {
                    break;
                }
            }

            // Try to start the next animation
            if let Some(next) = self.queue.pop_front() {
                let active = ActiveAnimation::new(next);
                // Instant animations (duration 0) complete immediately
                if active.animation.duration_ms() == 0 {
                    if let Animation::LogMessage { ref text } = active.animation {
                        messages.push(text.clone());
                    }
                    // Don't set as current, loop again
                    continue;
                }
                self.current = Some(active);
                break;
            } else {
                break;
            }
        }

        messages
    }

    /// Skip all remaining animations. Returns all pending log messages.
    pub fn skip_all(&mut self) -> Vec<String> {
        let mut messages = Vec::new();

        if let Some(ref active) = self.current {
            if let Animation::LogMessage { ref text } = active.animation {
                messages.push(text.clone());
            }
        }
        self.current = None;

        while let Some(anim) = self.queue.pop_front() {
            if let Animation::LogMessage { ref text } = anim {
                messages.push(text.clone());
            }
        }

        messages
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_active_animation_progress() {
        let mut anim = ActiveAnimation::new(Animation::Pause { duration_ms: 100 });
        assert!((anim.progress() - 0.0).abs() < f64::EPSILON);
        anim.tick(50);
        assert!((anim.progress() - 0.5).abs() < f64::EPSILON);
        anim.tick(50);
        assert!(anim.is_done());
    }

    #[test]
    fn test_queue_instant_animations() {
        let mut queue = AnimationQueue::new();
        queue.push(Animation::LogMessage {
            text: "hello".into(),
        });
        queue.push(Animation::LogMessage {
            text: "world".into(),
        });

        let msgs = queue.tick(0);
        assert_eq!(msgs, vec!["hello", "world"]);
        assert!(!queue.is_animating());
    }

    #[test]
    fn test_queue_timed_then_instant() {
        let mut queue = AnimationQueue::new();
        queue.push(Animation::Pause { duration_ms: 100 });
        queue.push(Animation::LogMessage {
            text: "done".into(),
        });

        let msgs = queue.tick(33);
        assert!(msgs.is_empty());
        assert!(queue.is_animating());

        let msgs = queue.tick(100);
        assert_eq!(msgs, vec!["done"]);
        assert!(!queue.is_animating());
    }

    #[test]
    fn test_skip_all() {
        let mut queue = AnimationQueue::new();
        queue.push(Animation::Pause { duration_ms: 500 });
        queue.push(Animation::LogMessage {
            text: "skipped".into(),
        });
        queue.push(Animation::Pause { duration_ms: 300 });

        // Start the first animation
        queue.tick(10);
        assert!(queue.is_animating());

        let msgs = queue.skip_all();
        assert_eq!(msgs, vec!["skipped"]);
        assert!(!queue.is_animating());
    }
}
